name: Main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm test
      - run: npm run build
        env:
          REACT_APP_GRAPHQL_SERVER_URI: https://graphql.em.aasan.dev
      - run: npm run deploy
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOMAIN_HOSTED_ZONE: em.aasan.dev
          DOMAIN_GRAPHQL_SERVER: graphql.em.aasan.dev
